Fix MSVC compiler error in basic_ops.h (#93322)
https://github.com/pytorch/pytorch/pull/93069 introduces a compiler error in some internal Windows builds using MSVC:

```
stderr: d:\full-fbsource\xplat\caffe2\torch\csrc\autograd\functions\basic_ops.h(43): fatal error C1001: An internal error has occurred in the compiler.
```
This may be related to older versions of MSVC not recognizing the `[[maybe-unused]]` attribute: https://developercommunity.visualstudio.com/t/compiler-bug-on-parsing-maybe-unused-in-range-base/209488. This PR reverts the changes in `basic_ops.h` that resolves those errors.

Verified this fixes the internal jobs, and landed as [D42854205](https://www.internalfb.com/diff/D42854205).
Pull Request resolved: https://github.com/pytorch/pytorch/pull/93322
Approved by: https://github.com/Skylion007, https://github.com/albanD