Don't build test_cpp_rpc if torch is built without distributed support (#30587)
Summary:
On the latest master, I get link errors when building one of the tests:

```sh
/home/pbell/git/pytorch/build/../test/cpp/rpc/test_wire_serialization.cpp:23:
undefined reference to `torch::distributed::rpc::wireDeserialize(void const*, unsigned long)'
```

This seems to be caused by PR https://github.com/pytorch/pytorch/issues/29785 not working with `USE_DISTRIBUTED=0`.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/30587

Differential Revision: D18758625

Pulled By: jjlilley

fbshipit-source-id: 0ad0703acdbbac22bb4b8317370fbe2606fcb67e