FindBLAS.cmake: fix missing stdlib.h include
This is to make sure BLAS F2C auto detection does not fail because of
compiler warnings:

    error: implicit declaration of function 'exit'