Better error message for misconfigured torchbench model (#114827)
```
  File "/home/jansel/pytorch/./benchmarks/dynamo/torchbench.py", line 381, in load_model
    benchmark_cls.name = model_name
AttributeError: 'NoneType' object has no attribute 'name
```
becomes
```
  File "/home/jansel/pytorch/./benchmarks/dynamo/torchbench.py", line 381, in load_model
    raise NotImplementedError(f"{model_name}.Model is None")
NotImplementedError: torchrec_dlrm.Model is None
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/114827
Approved by: https://github.com/xuzhao9, https://github.com/yanboliang