[Sparse] Raise exception when expand is called on sparse tensor (#98365)
It's already not working, but this makes error message a bit more readable. I.e. it turns:
```
% python -c "import torch;x=torch.eye(3).to_sparse().expand(3,3)"
```

from
```
NotImplementedError: Could not run 'aten::as_strided' with arguments from the 'SparseCPU' backend.
```
to
```
RuntimeError: Expand is unsupported for Sparse tensors.
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/98365
Approved by: https://github.com/pearu, https://github.com/cpuhrsch