[PyTorch] Fix broken build caused by keyword missing on Windows (#53562)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/53562

On Windows when we try to build //xplat/caffe2/c10:c10Windows, it failed with an error like
```
stderr: buck-out\gen\83497cbb\xplat\caffe2\c10\c10Windows#header-mode-symlink-tree-only,headers\c10/macros/Macros.h(189): error C2220: warning treated as error - no 'object' file generated
buck-out\gen\83497cbb\xplat\caffe2\c10\c10Windows#header-mode-symlink-tree-only,headers\c10/macros/Macros.h(189): warning C4067: unexpected tokens following preprocessor directive - expected a newline
```
See log here: https://www.internalfb.com/intern/buck/build/6eaea1f8-e237-4860-9f3b-3a8edd2207c6/

This is because Windows doesn't support `__has_attribute` keyword. Here I'm changing the ordering of `if` and `elif` so that we don't hit that line when build in Windows.

Test Plan: buck build //xplat/caffe2/c10:c10Windows xplat/mode/windows

Reviewed By: kimishpatel, swolchok

Differential Revision: D26896510

fbshipit-source-id: d52438a3df7bf742e467a919f6ab4fed14484f22